CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR UNIQUE,
    firstname VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    passphrase VARCHAR NOT NULL;
);